# Main Site settings *** ENGLISH ***

baseURL = "http://www.senaite.com/"
languageCode = "en"
title = "SENAITE LIMS"
theme = "senaite"

[params]
  name="SENAITE Foundation"
  description = "SENAITE - Next Generation LIMS"
  mailto = "senaite@senaite.com"
  copyright = "SENAITE Foundation."

    # navigation (see partials/navigation.html)
    [params.navbar]

        [[params.navbar.list]]
            title = "SENAITE"
            href = "#main"

        [[params.navbar.list]]
            title = "Features"
            href = "#features"

        [[params.navbar.list]]
           title = "Service Providers"
           href = "#providers"

        [[params.navbar.list]]
            title = "Contact"
            href = "#contact"

    [params.providers]

        [[params.providers.list]]
            name = "RIDING BYTES"
            url = "http://ridingbytes.com"
            mail = "hello@ridingbytes.com"
            logo = "assets/logos/ridingbytes.png"
            slogan = "Professional Open Source Solutions"
            location = "Germany"

        [[params.providers.list]]
            name = "NARALABS"
            url = "https://naralabs.com"
            mail = "info@naralabs.com"
            logo = "assets/logos/naralabs.png"
            slogan = "LIMS Engineering and Consulting"
            location = "Barcelona"

    [params.team]

        [[params.team.list]]
            name = "Ramon Bartl"
            role = "Founder of the SENAITE Project, API and Frontend Specialist"
            portrait = "https://github.com/ramonski.png?s=50"

        [[params.team.list]]
            name = "Campbell MC Kellar-Basset"
            role = "Bika LIMS Guru, Backend Developer, Explorer"
            portrait = "https://github.com/rockfruit.png?s=50"

        [[params.team.list]]
            name = "Mike Metcalfe"
            role = "Backend Specialist"
            portrait = "https://github.com/mikejmets.png?s=50"

        [[params.team.list]]
            name = "Lunga Baliwe"
            role = "Backend Specialist"
            portrait = "https://github.com/Lunga001.png?s=50"